### ISSUE TITLE
安装提示 插件已损坏.

### ISSUE THREAD

**Issue by beforefxlt** [gongjunhao/seckill#2]
chrome版本 版本 63.0.3239.84（正式版本） （64 位）

**Comment by AceInAndroid** [comment]
+1

**Comment by gongjunhao** [comment]
### 安装失败原因暂未查明，可通过另一种方式安装
* 下载源码包：https://github.com/gongjunhao/seckill/archive/master.zip
*  解压：seckill-master.zip
*  打开chrome浏览器，设置 --> 更多工具 --> 扩展程序
*  勾选开发者模式
*  点击“加载已解压的扩展程序”按钮，选择解压目录下的src目录，点击“确定”，即可完成安装

**Comment by gongjunhao** [comment]
安装失败原因：
> Chrome 63 gives error - This extension may have been corrupted
* chrome 62版本可以正常使用，
* chrome 63版本需要升级配置，已修复，但是打包的crx包，无法启用，需要发布扩展程序至市场审核通过后方可使用，国内发布比较费事，暂时不发布。
* 建议采用哦上面那种模式安装
