### ISSUE TITLE
只能添加到购物车，并不能购买

### ISSUE THREAD

**Issue by chinhuko** [gongjunhao/seckill#5]
感觉有点困惑，秒杀的逻辑不是应该能够提前获得购买按钮，然后在设置的时间点去触发那个按钮，这样才能够购买。但是，我在使用时的体验是这样的。插件能够按照设置的时间去把物品添加到购物车，但是选择购买按钮那个元素时，直接是正常跳转到购买页面。
附上我分别加入购物车和购买的两个视频。
链接:`https://pan.baidu.com/s/1o0IO3L7cYvuVXYGQxUEJXw `
密码: ac2t

**Comment by gongjunhao** [comment]
感谢试用反馈，这确实是个bug，努力修复中，或者换成右键点击选中（这种操作不太人性化）

**Comment by gongjunhao** [comment]
请升级版本0.0.3，此bug已修复
左键跳转未能阻止，升级为右键选取目标按钮
如果发现有新的bug欢迎反馈 :)
